AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/BlockLength:
  Enabled: false