name: GitHub Pages
on:
    workflow_dispatch:
    page_build:
    release:
        types:
        - created
    #push:
    #    branches:
    #    - gh-pages
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ruby/setup-ruby@v1
              with:
                ruby-version: 3.3.1
                bundler-cache: true
            - run: |
                bundle install
                bundle exec jekyll b
            - name: Upload pages content
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: _site/

    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4