name: GitHub Pages
on:
    push:
        branches:
        - gh-pages
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ruby/setup-ruby@v1
              with:
                ruby-version: 3.3.1
                bundler-cache: true
            - run: 
                bundle install
                bundle exec jekyll b