name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Set Version
      run: |
        bundle exec rake "version[$TAG]"
        bundle lock
    - name: Detect source branch
      run: |
        git fetch --deepen 1
        SRC_BRANCH="$(git branch -r --contains ""$TAG""  | grep -vE '^\*' | sed 's/ //g' | sed 's/origin\///g' | head -n 1)"
        echo $SRC_BRANCH
        echo "SRC_BRANCH=$SRC_BRANCH" >> "$GITHUB_ENV"
    - name: Commit Changes
      run: |
        git config user.name "GitHub"
        git config user.email "git@github.com"
        git diff 
        git commit -m "Setting version to ${TAG}." -- ./lib/suboptparse/version.rb ./Gemfile.lock
        git log -n 2
        git push origin "HEAD:$SRC_BRANCH"
    - name: Publish to Ruby Gems
      run: bundle exec rake 'release[origin]'

