name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set Version
      run: bundle exec rake "version[$TAG]"
    - name: Run the default task
      run: bundle exec rake

