name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Set Version
      run: |
        bundle exec rake "version[$TAG]"
        bundle lock
    - name: Detect source branch
      run: |
        git fetch --deepen 1
        SRC_BRANCH="$(git branch -r --contains ""$TAG""  | grep -vE '^\*' | grep -v ' -> ' | sed 's/ //g' | sed 's/origin\///g' | head -n 1)"
        echo "SRC_BRANCH=$SRC_BRANCH" >> "$GITHUB_ENV"
    - name: Commit Changes
      run: |
        git config user.name "GitHub"
        git config user.email "git@github.com"
        git commit -m "Setting version to ${TAG}." -- ./lib/suboptparse/version.rb ./Gemfile.lock
        git push origin "HEAD:$SRC_BRANCH"
    - name: Publish to Ruby Gems
      run: bundle exec rake 'release[origin]'
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
    - name: GitHub Pages
      #env:
      #  GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #  GH_USER: basking2
      run: |
        bundle exec rake rdoc
        git checkout gh-pages
        mv rdoc "${TAG}"
        echo "${TAG}" >> _data/versions.csv
        git add "${TAG}" _data/versions.csv
        git config user.name "GitHub"
        git config user.email "git@github.com"
        git commit -m "Add ${TAG} documentation to pages."
        #git remote add http-origin https://$GH_USER:$GH_TOKEN@github.com/$GH_USER/suboptparse.git
        #git push http-origin gh-pages:gh-pages
        git push origin gh-pages:gh-pages
    - name: Trigger GitHub Pages Action
      run: gh workflow run gh-pages.yml --ref gh-pages
