name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Set Version
      run: bundle exec rake "version[$TAG]"
    - run: git config user.name "GitHub"
    - run: git config user.email "git@github.com"
    - run: git commit -m "Setting version to ${TAG}." ./lib/suboptparse/version.rb
    - name: Push updated version to origin branch.
      run: git push origin "$TAG":"$(git branch --contains v0.0.0  | grep -vE '^\*')"

